# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jaisal/sources/not-vim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jaisal/sources/not-vim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaisal/sources/not-vim/CMakeFiles /home/jaisal/sources/not-vim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaisal/sources/not-vim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nv

# Build rule for target.
nv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nv
.PHONY : nv

# fast build rule for target.
nv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/build
.PHONY : nv/fast

buffer.o: buffer.c.o
.PHONY : buffer.o

# target to build an object file
buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/buffer.c.o
.PHONY : buffer.c.o

buffer.i: buffer.c.i
.PHONY : buffer.i

# target to preprocess a source file
buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/buffer.c.i
.PHONY : buffer.c.i

buffer.s: buffer.c.s
.PHONY : buffer.s

# target to generate assembly for a file
buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/buffer.c.s
.PHONY : buffer.c.s

cursor.o: cursor.c.o
.PHONY : cursor.o

# target to build an object file
cursor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/cursor.c.o
.PHONY : cursor.c.o

cursor.i: cursor.c.i
.PHONY : cursor.i

# target to preprocess a source file
cursor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/cursor.c.i
.PHONY : cursor.c.i

cursor.s: cursor.c.s
.PHONY : cursor.s

# target to generate assembly for a file
cursor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/cursor.c.s
.PHONY : cursor.c.s

editor.o: editor.c.o
.PHONY : editor.o

# target to build an object file
editor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/editor.c.o
.PHONY : editor.c.o

editor.i: editor.c.i
.PHONY : editor.i

# target to preprocess a source file
editor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/editor.c.i
.PHONY : editor.c.i

editor.s: editor.c.s
.PHONY : editor.s

# target to generate assembly for a file
editor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/editor.c.s
.PHONY : editor.c.s

events.o: events.c.o
.PHONY : events.o

# target to build an object file
events.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/events.c.o
.PHONY : events.c.o

events.i: events.c.i
.PHONY : events.i

# target to preprocess a source file
events.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/events.c.i
.PHONY : events.c.i

events.s: events.c.s
.PHONY : events.s

# target to generate assembly for a file
events.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/events.c.s
.PHONY : events.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/main.c.s
.PHONY : main.c.s

nvlua.o: nvlua.c.o
.PHONY : nvlua.o

# target to build an object file
nvlua.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/nvlua.c.o
.PHONY : nvlua.c.o

nvlua.i: nvlua.c.i
.PHONY : nvlua.i

# target to preprocess a source file
nvlua.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/nvlua.c.i
.PHONY : nvlua.c.i

nvlua.s: nvlua.c.s
.PHONY : nvlua.s

# target to generate assembly for a file
nvlua.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/nvlua.c.s
.PHONY : nvlua.c.s

window.o: window.c.o
.PHONY : window.o

# target to build an object file
window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/window.c.o
.PHONY : window.c.o

window.i: window.c.i
.PHONY : window.i

# target to preprocess a source file
window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/window.c.i
.PHONY : window.c.i

window.s: window.c.s
.PHONY : window.s

# target to generate assembly for a file
window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nv.dir/build.make CMakeFiles/nv.dir/window.c.s
.PHONY : window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nv"
	@echo "... buffer.o"
	@echo "... buffer.i"
	@echo "... buffer.s"
	@echo "... cursor.o"
	@echo "... cursor.i"
	@echo "... cursor.s"
	@echo "... editor.o"
	@echo "... editor.i"
	@echo "... editor.s"
	@echo "... events.o"
	@echo "... events.i"
	@echo "... events.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... nvlua.o"
	@echo "... nvlua.i"
	@echo "... nvlua.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

